### ISSUE TITLE
Plug-in Assembly Load Errors in 3ds Max Design 2015 SP3

### ISSUE THREAD

**Issue by EricChadwick** [timhawker/nlm3#3]
3ds Max Design 2015, service pack 3.
Product Version: 17.0 SP3 Commercial
OS: Windows 8.1

I installed the NLM3 DLLs as indicated in the Readme, then launched Max. These error messages appear:

---
## Plug-in Assembly Load Error

The assembly "NestedLayerManager.dll" encountered an error while loading.
It is possible that this error put the application in a bad state. The application will continue to run, but we recommend quitting the application, removing the plug-in, and restarting.
File: C:\Program Files\Autodesk\3ds Max Design 2015\bin\assemblies\NestedLayerManager.dll
Full Error: System.BadImageFormatException: Could not load file or assembly 'file:///C:\Program Files\Autodesk\3ds Max Design 2015\bin\assemblies\NestedLayerManager.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'file:///C:\Program Files\Autodesk\3ds Max Design 2015\bin\assemblies\NestedLayerManager.dll'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at AssemblyLoader.Loader.LoadAssembly(String file)
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
## OK   

---
## Plug-in Assembly Load Error

The assembly "ObjectListView.dll" encountered an error while loading.
It is possible that this error put the application in a bad state. The application will continue to run, but we recommend quitting the application, removing the plug-in, and restarting.
File: C:\Program Files\Autodesk\3ds Max Design 2015\bin\assemblies\ObjectListView.dll
Full Error: System.BadImageFormatException: Could not load file or assembly 'file:///C:\Program Files\Autodesk\3ds Max Design 2015\bin\assemblies\ObjectListView.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'file:///C:\Program Files\Autodesk\3ds Max Design 2015\bin\assemblies\ObjectListView.dll'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at AssemblyLoader.Loader.LoadAssembly(String file)
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
## OK   

Then Max seems to finish loading OK. I am going to re-install my older version from Tim, which was compiled in Dec 2015.

**Comment by EricChadwick** [comment]
Oops, my older version is NLM2, compiled in Dec 2014. Loads fine.
